### ISSUE TITLE
Not working with Azure Open AI API

### ISSUE THREAD

**Issue by nirzaf** [lee88688/aider-composer#46]
I am experiencing an issue with the Azure OpenAI API. The API is not functioning as expected, and I'm unable to retrieve responses.

Steps to Reproduce:

Attempt to call the Azure OpenAI API endpoint.
Expected Behavior:
The API should return a valid response with the generated text.

Actual Behavior:
No Response at all

Please fix it

**Comment by Rzhevskii** [comment]
I’m facing the same issue. The Azure OpenAI API works perfectly with the Aider CLI, but it does not return any response when using the Aider Composer extension in VSCode. The configurations differ slightly, as the extension does not allow specifying all the necessary Azure OpenAI parameters (e.g., API version). This seems to be an issue with how the extension handles Azure-specific configurations.

**Comment by rrichc** [comment]
@nirzaf @Rzhevskii A workaround for this is to set-up LiteLLM as a local proxy server, then configure Aider Composer to connect to a OpenAI compatible endpoint.

https://docs.litellm.ai/docs/proxy/docker_quick_start

1. Install the litellm CLI with PIP
2. Create the `litellm_config.yaml` with your Azure details
```
# https://github.com/BerriAI/litellm/blob/main/proxy_server_config.yaml
model_list:
  - model_name: DEPLOYMENT_NAME
    litellm_params:
      model: azure/DEPLOYMENT_NAME
      api_base: https://RESOURCE_GROUP_NAME.openai.azure.com/
      api_version: API_VERSION
      api_key: API_KEY
```
3. `litellm --config litellm_config.yaml` to start the proxy server
4. Set-up Aider Composer as below. Use anything for the API key, it doesn't matter.

<img width="383" alt="Image" src="https://github.com/user-attachments/assets/4f5b7210-c095-4812-b43c-4fd056250d7e" />
